name: haskell-data-science
version: 0.1.0.0
github: 'githubuser/haskell-data-science'
license: BSD3
author: 'Jacob Alford'
maintainer: 'jacob.alford@me.com'
copyright: 'Copyright © 2020 Jacob Alford'

extra-source-files:
  - README.md
  - ChangeLog.md

description: Please see the README on GitHub at <https://github.com/jacob_alford/haskell-data-science#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - filepath
  - containers
  - HTTP

library:
  source-dirs: src

executables:
  haskell-data-science-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-data-science

tests:
  haskell-data-science-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-data-science
